$(document).ready(function()
{
    $("#log").validate(
        {
            rules:
            {
                email:
                {
                    required:true,
                    minlength:4,
                    email:true
                    
                },
                pass:
                {
                    required:true,
                    minlength:6,
                    maxlength:15
                }
            }
        }
    )
})